/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PurchasableLicenseManagerInterface extends ethers.utils.Interface {
  functions: {
    "NAME()": FunctionFragment;
    "createAndRegisterNFT(address,tuple,uint256,uint8)": FunctionFragment;
    "description()": FunctionFragment;
    "holdsLicense(address,uint256,address)": FunctionFragment;
    "purchase(address,uint256,address,uint256)": FunctionFragment;
    "purchaseToken()": FunctionFragment;
    "registerNFT(address,uint256,address,uint256,uint8)": FunctionFragment;
    "registeredNFTs(address,uint256)": FunctionFragment;
    "royaltiesAddress()": FunctionFragment;
    "squadNft()": FunctionFragment;
    "unregisterNFT(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "NAME", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createAndRegisterNFT",
    values: [
      string,
      { contentURI: string; metadataURI: string },
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "holdsLicense",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "purchase",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerNFT",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredNFTs",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltiesAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "squadNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unregisterNFT",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "NAME", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAndRegisterNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holdsLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltiesAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "squadNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unregisterNFT",
    data: BytesLike
  ): Result;

  events: {
    "NFTRegistered(address,uint256,address,uint256,uint8,address)": EventFragment;
    "NFTUnregistered(address,uint256)": EventFragment;
    "Purchase(address,uint256,address,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NFTRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTUnregistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Purchase"): EventFragment;
}

export class PurchasableLicenseManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PurchasableLicenseManagerInterface;

  functions: {
    NAME(overrides?: CallOverrides): Promise<[string]>;

    createAndRegisterNFT(
      creator: string,
      data: { contentURI: string; metadataURI: string },
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    description(overrides?: CallOverrides): Promise<[string]>;

    holdsLicense(
      nftAddress: string,
      nftId: BigNumberish,
      holder: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    purchase(
      nftAddress: string,
      nftId: BigNumberish,
      purchaser: string,
      numberToBuy: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    purchaseToken(overrides?: CallOverrides): Promise<[string]>;

    registerNFT(
      nftAddress: string,
      nftId: BigNumberish,
      registrant: string,
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registeredNFTs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, string] & {
        price: BigNumber;
        sharePercentage: number;
        licenseToken: string;
      }
    >;

    royaltiesAddress(overrides?: CallOverrides): Promise<[string]>;

    squadNft(overrides?: CallOverrides): Promise<[string]>;

    unregisterNFT(
      nftAddress: string,
      nftId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  NAME(overrides?: CallOverrides): Promise<string>;

  createAndRegisterNFT(
    creator: string,
    data: { contentURI: string; metadataURI: string },
    price: BigNumberish,
    sharePercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  description(overrides?: CallOverrides): Promise<string>;

  holdsLicense(
    nftAddress: string,
    nftId: BigNumberish,
    holder: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  purchase(
    nftAddress: string,
    nftId: BigNumberish,
    purchaser: string,
    numberToBuy: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  purchaseToken(overrides?: CallOverrides): Promise<string>;

  registerNFT(
    nftAddress: string,
    nftId: BigNumberish,
    registrant: string,
    price: BigNumberish,
    sharePercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registeredNFTs(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, string] & {
      price: BigNumber;
      sharePercentage: number;
      licenseToken: string;
    }
  >;

  royaltiesAddress(overrides?: CallOverrides): Promise<string>;

  squadNft(overrides?: CallOverrides): Promise<string>;

  unregisterNFT(
    nftAddress: string,
    nftId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    NAME(overrides?: CallOverrides): Promise<string>;

    createAndRegisterNFT(
      creator: string,
      data: { contentURI: string; metadataURI: string },
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    description(overrides?: CallOverrides): Promise<string>;

    holdsLicense(
      nftAddress: string,
      nftId: BigNumberish,
      holder: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    purchase(
      nftAddress: string,
      nftId: BigNumberish,
      purchaser: string,
      numberToBuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    purchaseToken(overrides?: CallOverrides): Promise<string>;

    registerNFT(
      nftAddress: string,
      nftId: BigNumberish,
      registrant: string,
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    registeredNFTs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, string] & {
        price: BigNumber;
        sharePercentage: number;
        licenseToken: string;
      }
    >;

    royaltiesAddress(overrides?: CallOverrides): Promise<string>;

    squadNft(overrides?: CallOverrides): Promise<string>;

    unregisterNFT(
      nftAddress: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    NFTRegistered(
      nftAddress?: null,
      nftId?: null,
      registrant?: null,
      price?: null,
      sharePercentage?: null,
      licenseTokenAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, number, string],
      {
        nftAddress: string;
        nftId: BigNumber;
        registrant: string;
        price: BigNumber;
        sharePercentage: number;
        licenseTokenAddress: string;
      }
    >;

    NFTUnregistered(
      nftAddress?: null,
      nftId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { nftAddress: string; nftId: BigNumber }
    >;

    Purchase(
      nftAddress?: null,
      nftId?: null,
      purchaser?: null,
      licensesBought?: null,
      price?: null,
      licenseTokenAddress?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, BigNumber, string],
      {
        nftAddress: string;
        nftId: BigNumber;
        purchaser: string;
        licensesBought: BigNumber;
        price: BigNumber;
        licenseTokenAddress: string;
      }
    >;
  };

  estimateGas: {
    NAME(overrides?: CallOverrides): Promise<BigNumber>;

    createAndRegisterNFT(
      creator: string,
      data: { contentURI: string; metadataURI: string },
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    description(overrides?: CallOverrides): Promise<BigNumber>;

    holdsLicense(
      nftAddress: string,
      nftId: BigNumberish,
      holder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    purchase(
      nftAddress: string,
      nftId: BigNumberish,
      purchaser: string,
      numberToBuy: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    purchaseToken(overrides?: CallOverrides): Promise<BigNumber>;

    registerNFT(
      nftAddress: string,
      nftId: BigNumberish,
      registrant: string,
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registeredNFTs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    royaltiesAddress(overrides?: CallOverrides): Promise<BigNumber>;

    squadNft(overrides?: CallOverrides): Promise<BigNumber>;

    unregisterNFT(
      nftAddress: string,
      nftId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createAndRegisterNFT(
      creator: string,
      data: { contentURI: string; metadataURI: string },
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    description(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    holdsLicense(
      nftAddress: string,
      nftId: BigNumberish,
      holder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    purchase(
      nftAddress: string,
      nftId: BigNumberish,
      purchaser: string,
      numberToBuy: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    purchaseToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerNFT(
      nftAddress: string,
      nftId: BigNumberish,
      registrant: string,
      price: BigNumberish,
      sharePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registeredNFTs(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    royaltiesAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    squadNft(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unregisterNFT(
      nftAddress: string,
      nftId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
