/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC721Squad, IERC721SquadInterface } from "../IERC721Squad";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        components: [
          {
            internalType: "string",
            name: "contentURI",
            type: "string",
          },
          {
            internalType: "string",
            name: "metadataURI",
            type: "string",
          },
        ],
        internalType: "struct IERC721Squad.TokenData",
        name: "data",
        type: "tuple",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC721Squad__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721SquadInterface {
    return new utils.Interface(_abi) as IERC721SquadInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721Squad {
    return new Contract(address, _abi, signerOrProvider) as IERC721Squad;
  }
}
